resources:
  - name: binary-builder
    type: git
    source:
      uri: https://github.com/cloudfoundry/binary-builder.git
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: builds-out
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
  - name: nginx-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ nginx-builds.yml ]
  - name: php-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ php-builds.yml ]
  - name: php7-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ php7-builds.yml ]
  - name: node-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ node-builds.yml ]
  - name: ruby-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ ruby-builds.yml ]
  - name: jruby-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ jruby-builds.yml ]
  - name: httpd-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ httpd-builds.yml ]
  - name: python-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ python-builds.yml ]
  - name: bundler-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ bundler-builds.yml ]
  - name: build-tar
    type: s3
    source:
      bucket: pivotal-buildpacks
      versioned_file: /concourse-artifacts/binary-builder-source.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: godep-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ godep-builds.yml ]
  - name: concourse2tracker
    type: concourse2tracker
  - name: failure-alert
    type: slack-notification
    source:
      url: {{concourse-job-failure-notifications-slack-webhook}}
  - name: php-buildpack
    type: git
    source:
      uri: git@github.com:cloudfoundry/php-buildpack.git
      private_key: {{php-buildpack-private-key}}
      branch: develop
      ignore_paths:
        - VERSION
        - CHANGELOG
  - name: go-buildpack
    type: git
    source:
      uri: git@github.com:cloudfoundry/go-buildpack.git
      private_key: {{go-buildpack-private-key}}
      branch: develop
      ignore_paths:
        - VERSION
        - CHANGELOG
  - name: cf-edge-environments
    type: pool
    source:
      branch: resource-pools
      pool: cf-edge-environments
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
  - name: godep-new-releases
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      branch: new-release-notifications
      private_key: {{buildpacks-ci-private-key}}
      paths: [ godep.yaml ]
  - name: composer-new-releases
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      branch: new-release-notifications
      private_key: {{buildpacks-ci-private-key}}
      paths: [ composer.yaml ]
  - name: composer-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-ci-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      paths: [ composer-builds.yml ]

jobs:
  - name: binary-builder
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: binary-builder
          trigger: true
      - do:
        - aggregate:
          - task: rspec-1
            file: buildpacks-ci/tasks/binary-builder.yml
            params: { TOTAL_GROUPS: 4, CURRENT_GROUP: 1 }
            privileged: true
          - task: rspec-2
            file: buildpacks-ci/tasks/binary-builder.yml
            params: { TOTAL_GROUPS: 4, CURRENT_GROUP: 2 }
            privileged: true
          - task: rspec-3
            file: buildpacks-ci/tasks/binary-builder.yml
            params: { TOTAL_GROUPS: 4, CURRENT_GROUP: 3 }
            privileged: true
          - task: rspec-4
            file: buildpacks-ci/tasks/binary-builder.yml
            params: { TOTAL_GROUPS: 4, CURRENT_GROUP: 4 }
            privileged: true
