resources:
  - name: ci-master
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci
      branch: master
      private_key: {{buildpacks-ci-private-key}}
  - name: ci-develop
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: develop
  - name: concourse2tracker
    type: concourse2tracker

jobs:
  - name: merge-to-master
    serial: true
    plan:
      - aggregate:
        - get: ci-master
        - get: buildpacks-ci
          resource: ci-develop
          trigger: true
      - task: rspec
        file: buildpacks-ci/tasks/buildpacks-ci.yml
        params:
          CI_USERNAME: buildpacks
          CI_PASSWORD: {{concourse_basic_auth_password}}
          GITHUB_USERNAME: {{github-username}}
          GITHUB_PASSWORD: {{github-password}}
          GITHUB_ACCESS_TOKEN: {{buildpacks-github-token}}
        privileged: true
